# Generated by Django 5.0.4 on 2024-05-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("country", models.CharField(max_length=70, verbose_name="Страна")),
                ("town", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                (
                    "house_num",
                    models.CharField(max_length=10, verbose_name="Номер дома"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма долга"
                    ),
                ),
            ],
            options={
                "verbose_name": "Долг",
                "verbose_name_plural": "Долги",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название продукта"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(max_length=100, verbose_name="Модель"),
                ),
                (
                    "date_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата выпуска"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название завода"
                    ),
                ),
                (
                    "date_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="factories",
                        to="provider.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завод",
                "verbose_name_plural": "Заводы",
            },
        ),
        migrations.CreateModel(
            name="Entrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Предприниматель"
                    ),
                ),
                ("supplier_id", models.PositiveIntegerField()),
                (
                    "date_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "debt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider.debt",
                        verbose_name="Долг",
                    ),
                ),
                (
                    "supplier_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "provider"),
                            ("model__in", ["factory", "retail"]),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="entrepreneurs",
                        to="provider.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предприниматель",
                "verbose_name_plural": "Предприниматели",
            },
        ),
        migrations.CreateModel(
            name="Retail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название сети"
                    ),
                ),
                ("supplier_id", models.PositiveIntegerField()),
                (
                    "date_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "debt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider.debt",
                        verbose_name="Долг",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="retails",
                        to="provider.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "supplier_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "provider"),
                            ("model__in", ["factory", "entrepreneur"]),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розничная сеть",
                "verbose_name_plural": "Розничные сети",
            },
        ),
    ]
