# Generated by Django 5.0.4 on 2024-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneur",
            name="product",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="entrepreneurs",
                to="provider.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="retail",
            name="product",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="retails",
                to="provider.product",
                verbose_name="Продукты",
            ),
        ),
    ]
