# Generated by Django 5.0.4 on 2024-05-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0003_factory_supplier_name_retail_supplier_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factory",
            name="supplier_name",
        ),
        migrations.RemoveField(
            model_name="retail",
            name="supplier_name",
        ),
    ]
