# Generated by Django 5.0.4 on 2024-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0004_remove_factory_supplier_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retail",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма долга"
            ),
        ),
    ]
