# Generated by Django 5.0.4 on 2024-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0005_alter_retail_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneur",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма долга"
            ),
        ),
        migrations.DeleteModel(
            name="Debt",
        ),
    ]
