# Generated by Django 5.0.4 on 2024-05-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0006_alter_entrepreneur_debt_delete_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retail",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="provider.contact",
                verbose_name="Контакты",
            ),
        ),
    ]
